# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hive-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

