apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: hive 
  namespace: flux-system
spec:
  image: ghcr.io/abecker7/hivebox
  interval: 1m
  secretRef:
    name: ghcr-secret
